function rerun_fake_opt(savename_date_version, n_best)

savename = '_opt_test';
if exist('savename_date_version', 'var')
    savename = strcat(savename_date_version, savename);
end

% n_best = 1; %%


savename_base = '2022_03_02_fake_opt_top20_test_0_baseline';
loadfile = '2021_11_18_Quest_ps_init_20210927opt_inhib-bux-fix_250cpu_4hr_best112';

jobs = cell(n_best, 1);

for i = 1:n_best
    
        
    fprintf("Starting run %i\n", i)

    warning off

%     savename = strcat(savename_base, '_init_', num2str(i));

    opt_output = run_dynamic_EM(...
    'ecoli_butanol_inhib_fix_model',...
    'Options_struct_loadfile','2021_04_01_ecoli_approx_loadfile',...
    'best_ks_loadfile',loadfile,...
    'k_range',[0, 1e4],...
    'unknown_sat_constant_range',[0.01, 1],...
    'rate_constant_bounds',[0.1, 10],...
    'sat_constant_bounds',[0.1, 10],...
    'n_init_ksets',n_best,...
    'opt_alg','patternsearch',...
    'best_n_ksets',[],...
    'unknown_Ki_range', [5e-1, 5e1],...
    'dataset_for_sampling',1,...
    'manual_k_ranges',[444,1,40;445,0.1,2;449,0.1,1;40,10000,1000000;19,200,4000;682,0.1,2;683,1,100;685,0.005,0.5;611,0.1,4;61,3,30],...
    'optim_rate_const_bounds', [0, 1e4],...
    'optim_sat_const_bounds',[1e-3, 1e2],...
    'optim_inhib_const_bounds',[1e-1, 1e2],...
    'best_n_ksets_as_init', n_best,...
    'best_init_kset_inds', i,...
    'metab_fitness_multipliers',{'succ_c',6;'1btoh_c',20},...
    'exp_conditions', [3,4],...
    'optim_param_bounds', [],...
    'MaxTime',2*60,...
    'use_log_params',true,...
    'UseParallel',true,...
    'use_mex', false,...
    'run_fake_optimization', true);

    fprintf("Finished run %i\n", i)
    
    savestruct.EM_PR_combined.last_metab_concs(:, i) = opt_output.opt_PR.last_metab_concs;
    savestruct.EM_PR_combined.fitness_values(i, :) = opt_output.opt_PR.fitness_values;
    savestruct.EM_PR_combined.avg_fitness_values(i, :) = opt_output.opt_PR.avg_fitness_values;
    savestruct.EM_PR_combined.complete_times(:, i) = opt_output.opt_PR.complete_times;
    savestruct.EM_PR_combined.ode_warn_flags(:, i) = opt_output.opt_PR.ode_warn_flags;
    savestruct.EM_PR_combined.timepoints(:, i) = opt_output.opt_PR.timepoints;

    savestruct.EM_population(:, i) = opt_output.opt_params;

end


% fn = fieldnames(opt_output)
savestruct.model = opt_output.model;
savestruct.Experimental_Data = opt_output.Experimental_Data;
savestruct.Options = opt_output.Options;

save(savename, '-struct', 'savestruct')
