% Helper function to use Jacobian in ODE solver by pulling claculated
% jacobian from mass_balance

function dfdx = get_jacobian_from_mass_balance_fxn(...
    t, x, k, sat_constants, S_f_b,...
    sat_rxn_enzyme_species_inds, sat_rxn_inds, ...
    mass_action_elem_rxns, mult_sat_elem_rxns, add_sat_elem_rxns,...
    fixed_met_subs_rxns, fixed_met_timepoints, fixed_met_concs)

[~,~,dfdx] = mass_balance_ode_approx_rates(t, x, k, sat_constants, S_f_b,...
    sat_rxn_enzyme_species_inds, sat_rxn_inds, ...
    mass_action_elem_rxns, mult_sat_elem_rxns, add_sat_elem_rxns,...
    fixed_met_subs_rxns, fixed_met_timepoints, fixed_met_concs);

end